### ISSUE TITLE
Tests (code formatting) fails under pypy3

### ISSUE THREAD

**Issue by stefankoegl** [gpodder/mygpo#252]
See eg https://travis-ci.com/gpodder/mygpo/jobs/234899399#L357

````
$ make check-code-format
black --check --py36 --skip-string-normalization mygpo/
--py36 is deprecated and will be removed in a future version. Use --target-version py36 instead.
Traceback (most recent call last):
  File "/home/travis/virtualenv/pypy3.6-7.1.1/bin/black", line 10, in <module>
    sys.exit(patched_main())
  File "/home/travis/virtualenv/pypy3.6-7.1.1/site-packages/black.py", line 3754, in patched_main
    main()
  File "/home/travis/virtualenv/pypy3.6-7.1.1/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/pypy3.6-7.1.1/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/pypy3.6-7.1.1/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/pypy3.6-7.1.1/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/pypy3.6-7.1.1/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/travis/virtualenv/pypy3.6-7.1.1/site-packages/black.py", line 445, in main
    executor=executor,
  File "/opt/python/pypy3.6-7.1.1/lib-python/3/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/opt/python/pypy3.6-7.1.1/lib-python/3/asyncio/futures.py", line 255, in result
    raise self._exception
  File "/opt/python/pypy3.6-7.1.1/lib-python/3/asyncio/tasks.py", line 179, in _step
    result = coro.send(None)
  File "/home/travis/virtualenv/pypy3.6-7.1.1/site-packages/black.py", line 557, in schedule_formatting
    write_cache(cache, sources_to_cache, mode)
  File "/home/travis/virtualenv/pypy3.6-7.1.1/site-packages/black.py", line 3724, in write_cache
    os.replace(f.name, cache_file)
TypeError: 'PosixPath' does not support the buffer interface
makefile:44: recipe for target 'check-code-format' failed
make: *** [check-code-format] Error 1
The command "make check-code-format" exited with 2.
````

This might be caused by psf/black#780.

**Comment by SiqingYu** [comment]
Why does mygpo have a Travis build on PyPy?

**Comment by stefankoegl** [comment]
Why not? ;) It currently does not run on pypy, but we do a lot of JSON parsing and other operations that could benefit from it.

**Comment by SiqingYu** [comment]
Allow test failures for pypy3 · gpodder/mygpo@23ee10e

**Comment by stefankoegl** [comment]
I'm not sure if I understand your comment. There are currently some known issues with running on pypy, but I still found it worthwhile to run the tests and keep track of blockers.
